site_name: Factor-Based Commodity Investing
repo_url: https://github.com/tlorans/commo_factors
theme:
  name: readthedocs
  features:
    - navigation.tabs

nav:
  # - Home: index.md
  # - Introduction: intro.md
  - Factor Investing in Commodities: factor_investing.md
  - Is Physical Risk Priced?: is_physical_risk_priced.md
  # - Multi-Factor Portfolio: portfolio_construction.md
  # - Comparison with Indices: comparison_vs_index.md
  # - Concerns about Cyclone Activity: concerns.md
  # - Dynamic Strategies: predictability.md


extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js