site_name: Factor-Based Commodity Investing
repo_url: https://github.com/tlorans/commo_factors
theme:
  name: readthedocs
  features:
    - navigation.tabs

nav:
  - Home: index.md
  - Introduction: intro.md
  - Priced Factors: priced_factors.md
  - Multi-Factor Portfolio: portfolio_construction.md
  - Comparison with Indices: comparison_vs_index.md
  - Dynamic Strategies: predictability.md
